// packages/vue-infinite-viewer/src/InfiniteViewer.vue
<template>
    <div v-bind:class="className || defaultClassName" ref="containerElement">
        <div ref="wrapperElement">
            <div ref="scrollAreaElement"></div>
            <slot />
        </div>
        <div ref="horizontalScrollElement">
            <div class="infinite-viewer-scroll-thumb"></div>
        </div>
        <div ref="verticalScrollElement">
            <div class="infinite-viewer-scroll-thumb"></div>
        </div>
    </div>
</template>
<script lang="ts">
import VanillaInfiniteViewer, {
    InfiniteViewerOptions, OPTIONS, EVENTS, PROPERTIES, METHODS,
} from 'infinite-viewer';
import { isUndefined } from '@daybrush/utils';

const methods = {};

METHODS.forEach(name => {
    methods[name] = function (this: any, ...args: any[]) {
        this.infiniteViewer[name](...args);
    };
});

export default {
    methods,
    props: OPTIONS,
    mounted() {
        const options: Partial<InfiniteViewerOptions> = {};
        const props = this.$props;
        OPTIONS.forEach((name) => {
            const value = props[name];

            if (!isUndefined(value)) {
                options[name as any] = props[name];
            }
        });
        const refs = this.$refs;

        this.infiniteViewer = new VanillaInfiniteViewer(
            refs.containerElement as HTMLElement,
            (refs.scrollAreaElement as HTMLElement).nextElementSibling as HTMLElement,
            {
                ...options,
                wrapperElement: refs.wrapperElement as HTMLElement,
                scrollAreaElement: refs.scrollAreaElement as HTMLElement,
                horizontalScrollElement: refs.horizontalScrollElement as HTMLElement,
                verticalScrollElement: refs.verticalScrollElement as HTMLElement,
            },
        );

        const infiniteViewer = this.infiniteViewer;

        EVENTS.forEach((name) => {
            infiniteViewer.on(name, (e) => {
                this.$emit(name, { ...e });
            });
        });
    },
    updated() {
        const props = this.$props;
        const infiniteViewer = this.infiniteViewer;

        PROPERTIES.forEach((name) => {
            const value = props[name];

            if (infiniteViewer[name] !== value && !isUndefined(value)) {
                (infiniteViewer as any)[name] = props[name];
            }
        });
    },
    beforeDestroy() {
        this.infiniteViewer.destroy();
    },
    unmounted() {
        this.infiniteViewer.destroy();
    },
};
</script>

// packages/svelte-infinite-viewer/src/svelte-infinite-viewer/InfiniteViewer.svelte
<script>
  import VanillaInfiniteViewer, {
    OPTIONS,
    PROPERTIES,
    EVENTS,
    CLASS_NAME
  } from "infinite-viewer";

  import {
    onMount,
    onDestroy,
    createEventDispatcher,
    beforeUpdate
  } from "svelte";

  const dispatch = createEventDispatcher();

  export let className = "";
  let infiniteViewer;

  let wrapperElement;
  let containerElement;
  let scrollAreaElement;
  let horizontalScrollElement;
  let verticalScrollElement;

  export function getInstance() {
    return infiniteViewer;
  }

  beforeUpdate(() => {
    if (!infiniteViewer) {
      return;
    }

    PROPERTIES.forEach(name => {
      if (name in $$props) {
        infiniteViewer[name] = $$props[name];
      }
    });
  });
  onMount(() => {
    const options = {};

    PROPERTIES.forEach(name => {
      if (name in $$props && typeof $$props[name] !== "undefined") {
        options[name] = $$props[name];
      }
    });

    infiniteViewer = new VanillaInfiniteViewer(
      containerElement,
      scrollAreaElement.nextElementSibling,
      {
        ...options,
        wrapperElement,
        scrollAreaElement,
        horizontalScrollElement,
        verticalScrollElement,
      },
    );

    EVENTS.forEach((name, i) => {
      infiniteViewer.on(name, e => {
        const result = dispatch(name, e);

        if (result === false) {
          e.stop();
        }
      });
    });
  });
  onDestroy(() => {
    infiniteViewer.destroy();
  });
</script>
<div class={`${className || ''} ${CLASS_NAME}`} bind:this={containerElement}>
    <div class="infinite-viewer-wrapper" bind:this={wrapperElement}>
        <div class="infinite-viewer-scroll-area" bind:this={scrollAreaElement}></div>
        <slot />
    </div>
    <div class="infinite-viewer-scroll-bar infinite-viewer-horizontal-scroll-bar" bind:this={horizontalScrollElement}>
        <div class="infinite-viewer-scroll-thumb"></div>
    </div>
    <div class="infinite-viewer-scroll-bar infinite-viewer-vertical-scroll-bar" bind:this={verticalScrollElement}>
        <div class="infinite-viewer-scroll-thumb"></div>
    </div>
</div>
